"""Added conditional allergy profile fields

Revision ID: 90543c2a4a61
Revises: b959ed091244
Create Date: 2026-07-01 15:17:53.586337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90543c2a4a61'
down_revision = 'b959ed091244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allergy_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_known_allergy', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('allergy_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reactive_ingredients', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('reaction_symptoms', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reaction_severity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('visited_dermatologist', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('taking_medication', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('additional_allergy_info', sa.Text(), nullable=True))
        batch_op.drop_column('known_allergies')
        batch_op.drop_column('skincare_reactions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allergy_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skincare_reactions', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('known_allergies', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('additional_allergy_info')
        batch_op.drop_column('taking_medication')
        batch_op.drop_column('visited_dermatologist')
        batch_op.drop_column('reaction_severity')
        batch_op.drop_column('reaction_symptoms')
        batch_op.drop_column('reactive_ingredients')
        batch_op.drop_column('allergy_type')
        batch_op.drop_column('has_known_allergy')

    # ### end Alembic commands ###
