"""Update diet profile fields

Revision ID: a168af23c851
Revises: 90543c2a4a61
Create Date: 2026-07-02 14:56:14.944748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a168af23c851'
down_revision = '90543c2a4a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diet_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fruits_veggies_intake', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fast_food_freq', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('alcohol_smoking', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tea_coffee_intake', sa.String(length=100), nullable=True))
        batch_op.alter_column('sugar_consumption',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diet_profiles', schema=None) as batch_op:
        batch_op.alter_column('sugar_consumption',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('tea_coffee_intake')
        batch_op.drop_column('alcohol_smoking')
        batch_op.drop_column('fast_food_freq')
        batch_op.drop_column('fruits_veggies_intake')

    # ### end Alembic commands ###
