"""Added more lifestyle profile fields

Revision ID: b959ed091244
Revises: d21022764068
Create Date: 2026-07-01 15:07:21.156416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b959ed091244'
down_revision = 'd21022764068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lifestyle_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_frequency', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('screen_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sunscreen_usage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('face_washing_frequency', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('makeup_usage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pollution_exposure', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('occupation_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lifestyle_profiles', schema=None) as batch_op:
        batch_op.drop_column('occupation_type')
        batch_op.drop_column('pollution_exposure')
        batch_op.drop_column('makeup_usage')
        batch_op.drop_column('face_washing_frequency')
        batch_op.drop_column('sunscreen_usage')
        batch_op.drop_column('screen_time')
        batch_op.drop_column('exercise_frequency')

    # ### end Alembic commands ###
