"""add stage_details and ai_analysis to analysis_results

Revision ID: c83edd64ce8f
Revises: 3053a11c34fe
Create Date: 2026-07-13 15:15:47.215278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83edd64ce8f'
down_revision = '3053a11c34fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_details', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ai_analysis', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_column('ai_analysis')
        batch_op.drop_column('stage_details')

    # ### end Alembic commands ###
