"""Added more skin profile fields

Revision ID: d21022764068
Revises: 43a0cca50eb7
Create Date: 2026-07-01 14:42:43.611148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21022764068'
down_revision = '43a0cca50eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skin_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skin_concerns', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pore_size', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('under_eye_issue', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lip_condition', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('seasonal_skin_changes', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skin_profiles', schema=None) as batch_op:
        batch_op.drop_column('seasonal_skin_changes')
        batch_op.drop_column('lip_condition')
        batch_op.drop_column('under_eye_issue')
        batch_op.drop_column('pore_size')
        batch_op.drop_column('skin_concerns')

    # ### end Alembic commands ###
